CREATE TABLE author (id NUMBER(10), name VARCHAR2(255) NOT NULL, PRIMARY KEY (id));

CREATE TABLE book (author_id NUMBER(10) NOT NULL, id NUMBER(10), name VARCHAR2(255) NOT NULL, PRIMARY KEY (id));

ALTER TABLE book ADD CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES author (id);

