CREATE TABLE author (id int GENERATED BY DEFAULT AS IDENTITY, name character varying(255) NOT NULL, CONSTRAINT author_pkey PRIMARY KEY (id));

CREATE TABLE book (author_id int NOT NULL, description character varying(255), id int GENERATED BY DEFAULT AS IDENTITY, name character varying(255) NOT NULL, CONSTRAINT book_pkey PRIMARY KEY (id));

CREATE TABLE bookorder (id int GENERATED BY DEFAULT AS IDENTITY, orderDate date NOT NULL, CONSTRAINT bookorder_pkey PRIMARY KEY (id));

CREATE TABLE bookorderitem (book_id int NOT NULL, id int GENERATED BY DEFAULT AS IDENTITY, order_id int NOT NULL, CONSTRAINT bookorderitem_pkey PRIMARY KEY (id));

ALTER TABLE book ADD CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES author (id);

ALTER TABLE bookorderitem ADD CONSTRAINT fk_bookorderitem_book FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE bookorderitem ADD CONSTRAINT fk_bookorderitem_bookorder FOREIGN KEY (order_id) REFERENCES bookorder (id);

