CREATE TABLE author (id INT IDENTITY(1,1), name NVARCHAR(255) NOT NULL, PRIMARY KEY (id));

CREATE TABLE book (author_id INT NOT NULL, id INT IDENTITY(1,1), name NVARCHAR(255) NOT NULL, PRIMARY KEY (id));

ALTER TABLE book ADD CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES author (id);

