CREATE TABLE author (id int GENERATED BY DEFAULT AS IDENTITY, name character varying(255) NOT NULL, CONSTRAINT author_pkey PRIMARY KEY (id));

CREATE TABLE book (author_id int NOT NULL, id int GENERATED BY DEFAULT AS IDENTITY, name character varying(255) NOT NULL, CONSTRAINT book_pkey PRIMARY KEY (id));

ALTER TABLE book ADD CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES author (id);

